name: capstone_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - quarto
  - tectonic
  - jupyter
  - ipykernel
  - pandas
  - matplotlib
  - seaborn
  - numpy
  - pytorch
  - torchvision
  - ultralytics
  - pip
  - pip:
      - dotenv
      - label-studio
      - label-studio-sdk