name: Python code coverage testing with pytest 

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ['3.11']
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        python-version: "3.11"
        activate-environment: "test-env"
        auto-activate-base: false
        channels: conda-forge,defaults
    
    - name: Install dependencies
      run: |
        which python
        conda env update -n test-env -f environment.yml
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        pytest tests/ --cov=src --cov-report=xml
