name: Python code coverage testing with pytest 

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ['3.11']
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        python-version: "3.11"
        activate-environment: "test-env"
        auto-activate-base: false
        channels: conda-forge,defaults
    
    - name: Install dependencies
      run: |
        which python
        conda env update -n test-env -f environment.yml
    
    - name: Test with pytest
      run: |
        source activate base
        conda activate test-env
        pytest tests/ --cov=src --cov-report=xml
